# Autogenerated wrapper script for ONNXRuntime_CUDA_jll for aarch64-linux-gnu-cxx11-cuda_platform+jetson-cuda+10.2
JLLWrappers.@generate_wrapper_header("ONNXRuntime_CUDA")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
